### ISSUE TITLE
Vectorlogo doesn't render

### ISSUE THREAD

**Issue by Ainali** [publiccodenet/bumperscripter#11]
I've tried to change the `vectorlogo` to another file that I put in the data folder, but it doesn't show up in the render anywhere. I don't think it does in the original script either since all the logos that are shown in the output are in the background png image.

**Comment by felixfaassen** [comment]
@Ainali I noticed it is dead code. the mark.svg is declared and read but never used. This is because the logo is part of the background. I will remove it
